[project]
name = "climate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Col Perks", email = "wild.fauve@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "clojos-common",
    "discord-webhook>=1.4.1",
    "matplotlib>=3.10.1",
    "notebook>=7.4.2",
    "pendulum>=3.1.0",
    "polars>=1.29.0",
    "pymonad>=2.4.0",
    "python-dotenv>=1.1.0",
    "rdflib>=7.1.4",
    "returns>=0.25.0",
    "rich>=13.9.4",
]

[tool.uv.sources]
clojos-common = { git = "https://github.com/wildfauve/clojos_common.git" }

[dependency-groups]
dev = [
    "pdbpp>=0.11.6",
    "pytest>=8.3.5",
    "pytest-env>=1.1.5",
    "ruff>=0.13.2",
]


[project.scripts]
climate = 'climate.cli.climate:run'
locale = "climate.cli.locale:cli"
temperature = "climate.cli.temperature:cli"
narrative = "climate.cli.narrative:cli"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
